# Generated by Django 2.2.2 on 2019-06-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpa', models.TextField()),
                ('vk_message', models.TextField(blank=True, null=True)),
                ('tg_message', models.TextField(blank=True, null=True)),
                ('vk', models.TextField(blank=True, null=True)),
                ('tg', models.TextField(blank=True, null=True)),
                ('vk_photo', models.TextField(blank=True, null=True)),
                ('tg_photo', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
